services:
  database:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USERNAME: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      WORKING_DIR: ${WORKING_DIR}
    volumes:
      - "${WORKING_DIR}:/var/lib/postgresql/data"
